Multi-OS Support; hidden password input
Abhijeetbyte/MYPmanager pull request #3
Opened 2022-10-01 19:00 UTC by lewismunday

- I have changed the clear terminal command to a function depending on OS (I would appreciate if Windows could be tested). 
- Using the getpass module, password inputs are now hidden from the screen (will only work running via the terminal, not shell).
- Changed some 'if !=' statements to 'if not'
- General filing reformat for spacing and readibility

2022-10-02 16:20 UTC, Abhijeetbyte requested changes
Hi, Lewis

I appreciate your efforts, you have added some really useful features, and I have tested your changes on windows machine, clear() function works fine. Although :
* You have removed `os.system('color')`, this is an essential line of code to display colored text with ANSI codes.

* Did not changed `input()` to `getpass()` in Edit feature


  Everything else works great and soon, release a variant for Linux

Thank You

2022-10-02 16:22 UTC, Abhijeetbyte commented on main.py
> +        Master_pass = getpass(" ENTER MASTER PASSWORD: ")  # get master password from user
add an "\n"

2022-10-02 16:23 UTC, Abhijeetbyte commented on main.py
>              new_password = input(" ENTER NEW PASSWORD: ")  # this will be encrypted
add a "\n"

2022-10-06 06:03 UTC, Abhijeetbyte commented
Hi, Lewis

kindly made the requested changes so, I can merge your pull request

2022-10-08 14:12 UTC, lewismunday commented
Hello, 

Thanks for your patience and review; I have been on holiday. I made the changes as per suggestion. Please take a moment to review

2022-10-08 15:07 UTC, Abhijeetbyte approved these changes

2022-10-08 15:08 UTC, Abhijeetbyte commented
Thank you Lewis for your contribution to this repository. I'm glad to merge your pull request

2022-10-08 15:08 UTC, merged